# Generated by Django 4.2.5 on 2023-10-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Armchair_number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='Surname',
            field=models.CharField(max_length=15),
        ),
    ]
