# Generated by Django 4.2.5 on 2023-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_user_armchair_number_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
